version: "3"
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5762"
     - "15672:15672"
  service-registry:
    image: "microservice/service-registry:0.0.1-SNAPSHOT"
    # build: ./service-registry
    ports: 
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka"
  gateway:
    image: "microservice/gateway:0.0.1-SNAPSHOT"
    # build: ./gateway
    ports: 
      - "8000:8000"
    depends_on:
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka"
  multiplication-service:
    image: "microservice/multiplication-service:0.0.1-SNAPSHOT"
    # build: ./multiplication-service
    depends_on:
      - rabbit
      - gateway
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka"
  gamification-service:
    image: "microservice/gamification-service:0.0.1-SNAPSHOT"
    # build: ./gamification-service
    depends_on:
      - rabbit
      - gateway
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka"
    
